# Server Network Settings
server.port=8888
server.thread-pool-size=20

# Security / SSL/TLS Settings (Set true in Production)
server.ssl.enabled=false
server.ssl.key-store-path=server.keystore
server.ssl.key-store-password=changeit

# Database Settings (For Production persistence)
db.url=jdbc:h2:mem:quizzlivedb
db.username=sa
db.password=
